// Root-level `_index.md` renderer — the vault's MOC (Map of Content).
// Pure — no I/O. Timestamp is supplied in stats.generatedAt.

import type { VaultStats } from "./types.ts";

function slugifyConcept(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || name;
}

function sortedEntries(map: Record<string, number>): Array<[string, number]> {
  return Object.entries(map).sort((a, b) => {
    if (b[1] !== a[1]) return b[1] - a[1];
    return a[0].localeCompare(b[0]);
  });
}

function section(title: string, lines: string[]): string[] {
  if (lines.length === 0) return [];
  return [`## ${title}`, "", ...lines, ""];
}

export function renderIndex(stats: VaultStats): string {
  const out: string[] = [];
  out.push("# ARRA Vault Index");
  out.push("");
  out.push(`Generated: ${stats.generatedAt.toISOString()}`);
  out.push("");
  out.push(`Total docs: ${stats.total}`);
  out.push("");

  const byType = sortedEntries(stats.byType).map(
    ([name, n]) => `- ${name}: ${n}`,
  );
  out.push(...section("By type", byType));

  const byProject = sortedEntries(stats.byProject).map(
    ([name, n]) => `- ${name}: ${n}`,
  );
  out.push(...section("By project", byProject));

  const concepts = stats.topConcepts.map(
    (c) => `- [[_concepts/${slugifyConcept(c.name)}|${c.name}]] (${c.count})`,
  );
  out.push(...section("Top concepts", concepts));

  if (stats.topLinked && stats.topLinked.length > 0) {
    const linked = stats.topLinked.map(
      (d) => `- [[${d.slug}]] (${d.linkCount} links)`,
    );
    out.push(...section("Top linked docs", linked));
  }

  out.push("---");
  out.push("");
  out.push(
    "Generated by ARRA Oracle `arra-cli export obsidian`. " +
    "Do not hand-edit `_index.md` — regenerate instead. " +
    "Hand-edit doc pages freely; re-export preserves `arra_id` frontmatter.",
  );
  out.push("");
  out.push(
    "Oracle Rule 6: this file was written by arra-oracle-v3, not a human.",
  );
  out.push("");

  return out.join("\n");
}
