#!/usr/bin/env bun
/**
 * gen-endpoints.ts — extract Hono route handlers from src/routes/*.ts and
 * rewrite the "API Endpoints" table in README.md between the markers:
 *
 *   <!-- endpoints:start -->
 *   ...table...
 *   <!-- endpoints:end -->
 *
 * Usage:
 *   bun run scripts/gen-endpoints.ts           # writes README.md in-place
 *   bun run scripts/gen-endpoints.ts --check   # exits 1 if README would change
 *   bun run scripts/gen-endpoints.ts --print   # prints the table to stdout
 */

import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join, basename } from 'path';

const ROUTES_DIR = join(import.meta.dirname, '..', 'src', 'routes');
const README = join(import.meta.dirname, '..', 'README.md');
const START = '<!-- endpoints:start -->';
const END = '<!-- endpoints:end -->';

type Endpoint = {
  method: string;
  path: string;
  module: string;
  line: number;
  desc?: string;
};

// Match `app.get('/api/x', ...)` / `.post(...)` / etc.
const ROUTE_RE = /app\.(get|post|put|patch|delete|options|head)\s*\(\s*['"`]([^'"`]+)['"`]/g;
// Comment immediately before the route (optional description)
const COMMENT_RE = /\/\/\s*(.+)\s*$/;

function extractEndpoints(): Endpoint[] {
  const files = readdirSync(ROUTES_DIR).filter((f) => f.endsWith('.ts')).sort();
  const eps: Endpoint[] = [];
  for (const f of files) {
    const text = readFileSync(join(ROUTES_DIR, f), 'utf8');
    const lines = text.split('\n');
    let m: RegExpExecArray | null;
    ROUTE_RE.lastIndex = 0;
    while ((m = ROUTE_RE.exec(text)) !== null) {
      const [, method, path] = m;
      const pre = text.slice(0, m.index);
      const lineNum = pre.split('\n').length;
      // Look at the previous non-blank line for a `//` comment describing this route
      let desc: string | undefined;
      for (let i = lineNum - 2; i >= Math.max(0, lineNum - 4); i--) {
        const raw = lines[i]?.trim();
        if (!raw) continue;
        const cm = raw.match(COMMENT_RE);
        if (cm) {
          desc = cm[1].trim();
          break;
        }
        if (raw.startsWith('*')) {
          desc = raw.replace(/^\*\s*/, '').trim();
          break;
        }
        break;
      }
      eps.push({ method: method.toUpperCase(), path, module: basename(f, '.ts'), line: lineNum, desc });
    }
  }
  return eps;
}

function toTable(eps: Endpoint[]): string {
  const groups = new Map<string, Endpoint[]>();
  for (const e of eps) {
    if (!groups.has(e.module)) groups.set(e.module, []);
    groups.get(e.module)!.push(e);
  }
  const lines: string[] = [];
  lines.push(`> Auto-generated by \`bun run scripts/gen-endpoints.ts\`. ${eps.length} endpoints across ${groups.size} modules.`);
  lines.push('');
  lines.push('| Method | Path | Module | Description |');
  lines.push('|--------|------|--------|-------------|');
  for (const [mod, list] of [...groups.entries()].sort()) {
    for (const e of list) {
      const desc = (e.desc ?? '').replace(/\|/g, '\\|');
      lines.push(`| \`${e.method}\` | \`${e.path}\` | \`${mod}\` | ${desc} |`);
    }
  }
  return lines.join('\n');
}

function patchReadme(table: string): { changed: boolean; next: string } {
  const cur = readFileSync(README, 'utf8');
  const si = cur.indexOf(START);
  const ei = cur.indexOf(END);
  if (si === -1 || ei === -1 || ei < si) {
    throw new Error(`README markers not found (${START} / ${END})`);
  }
  const before = cur.slice(0, si + START.length);
  const after = cur.slice(ei);
  const next = `${before}\n\n${table}\n\n${after}`;
  return { changed: next !== cur, next };
}

const argv = process.argv.slice(2);
const eps = extractEndpoints();
const table = toTable(eps);

if (argv.includes('--print')) {
  console.log(table);
  process.exit(0);
}

const { changed, next } = patchReadme(table);
if (argv.includes('--check')) {
  if (changed) {
    console.error('README.md is out of date. Run: bun run scripts/gen-endpoints.ts');
    process.exit(1);
  }
  console.log('README.md endpoints table up to date.');
  process.exit(0);
}

writeFileSync(README, next);
console.log(`${changed ? 'Updated' : 'No change to'} README.md — ${eps.length} endpoints written.`);
